on: push
name: Deploy website
jobs:
  web-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Fetch
      uses: actions/checkout@v3

    - name: Publish
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        server-dir: public_html/
        security: strict
        protocol: ftps
        port: 21
